### PR TITLE
Add initial project template

### PR DESCRIPTION
**Pull request by MMDPROJECT**
@Retriever5500 and @Navid-Ebadi-2003 please review the code.

### CODE REVIEW

**Comment by Retriever5500** [comment]
Okay checked the code and most of it is alright, however why did you create another package for Album and such? If you meant to use them for both client and server, then put them on shared. Also there are variables where you used snake case instead of camel case, which is what convention java uses. Convert them to camel case.

**Comment by MMDPROJECT** [comment]
@Retriever5500 Have done what you asked for. 
But also I have a question about design of most of the classes.
look at for example **Album** Class;
 `public class Album {
    private UUID albumId;
    private String title;
    private UUID artistId;
    private UUID genreId;
    private LocalDate releaseDate;
    private int popularity;
    private ArrayList<Music> tracks;
    `
In the database we are storing a column for each of the **Albums** called **tracks**, but that stores a Json array of UUIDs which is id of each music that is in that **Album** and that differs from what do we have in **Album** class. Do you think we are gonna have problem with it ?

**Comment by Retriever5500** [comment]
Actually, I think it's better if we only store the ID instead of the whole object inside the class, as imagine that a user wants to browse their playlists. We don't need to show the tracks of all playlists because the user is only browsing and may want to use only one playlist, so pulling all tracks of all playlists becomes unnecessary.

**Comment by MMDPROJECT** [comment]
Alright man I have changed the classes corresponding to what you have explained. @Retriever5500

**Comment by Retriever5500** [comment]
@MMDPROJECT Actually you haven't made the changes

**Comment by Retriever5500** [comment]
Also have you fixed the last issue? The one with the extra while loop

**Pull request merged**
