### PR TITLE
Search

### PR DESCRIPTION
**Pull request by Navid-Ebadi-2003**
search task was completed . please check it for sure . @MMDPROJECT @Retriever5500

### CODE REVIEW

**Comment by Retriever5500** [comment]
Okay will check in a moment

**Comment by Retriever5500** [comment]
@Navid-Ebadi-2003 what is `userInput` precisely? It's exactly what the user has typed inside the search bar, or are we adding something to it before running a query with it?

**Comment by Navid-Ebadi-2003** [comment]
> @Navid-Ebadi-2003 what is `userInput`? It's exactly what the user has typed inside the search bar?

yes

**Comment by Retriever5500** [comment]
> yes

Well then if we're simply going to pass it to query it'll actually return the results as if we are using the equal sign, as it's not using any wildcards. My suggestion is to add `%` to the beginning and the end of of the `userInput` so that it'll look for anything that has those said characters in them.
More on this:
[SQL LIKE](https://www.w3schools.com/SQL/sql_like.asp)

**Comment by Navid-Ebadi-2003** [comment]
> > yes
> 
> Well then if we're simply going to pass it to query it'll actually return the results as if we are using the equal sign, as it's not using any wildcards. My suggestion is to add `%` to the beginning and the end of of the `userInput` so that it'll look for anything that has those said characters in them. More on this: [SQL LIKE](https://www.w3schools.com/SQL/sql_like.asp)

The requested change was made. is it okay ?

**Comment by Retriever5500** [comment]
> The requested change was made. is it okay ?

Actually no, the `%` has to be inside the string, not outside of it. Add it to the string before passing it to the prepared statement
@Navid-Ebadi-2003

**Comment by Navid-Ebadi-2003** [comment]
> > The requested change was made. is it okay ?
> 
> Actually no, the `%` has to be inside the string, not outside of it. Add it to the string before passing it to the prepared statement @Navid-Ebadi-2003

oooh that's right :))) . i will fix that

**Comment by Navid-Ebadi-2003** [comment]
> > > The requested change was made. is it okay ?
> > 
> > 
> > Actually no, the `%` has to be inside the string, not outside of it. Add it to the string before passing it to the prepared statement @Navid-Ebadi-2003
> 
> oooh that's right :))) . i will fix that

it's done . please check

**Comment by Retriever5500** [comment]
LGTM, just instead of reassigning the value `userInput` it's better to define another variable like `pattern` for readability imo. Also this is very personal but I'm uncomfortable with it being above the query string. Other than that looks all good to me.
@Navid-Ebadi-2003

**Comment by Navid-Ebadi-2003** [comment]
> LGTM, just instead of reassigning the value `userInput` it's better to define another variable like `pattern` for readability imo. Also this is very personal but I'm uncomfortable with it being above the query string. Other than that looks all good to me. @Navid-Ebadi-2003

that's okay . i changed userInput to pattern and merged the branch

**Pull request merged**
