### PR TITLE
Completed Request & Response Classes for API

### PR DESCRIPTION
**Pull request by MMDPROJECT**
Completed these two classes for api.
please read the code and comments and tell me what do you think.
@Retriever5500 @Navid-Ebadi-2003 
(And also please be careful with the button "**Merge pull request**". 
I couldn't convert pull request to draft.)

### CODE REVIEW

**Comment by Retriever5500** [comment]
Okay good job with documenting the code. There are a few things though. I think it's more appropriate if we rename `jsonBody` to `requestBody` for the Request class and to `responseBody` for the Response class. Also, with `loginRes` I think we're sending insufficient data. We need to construct the whole user object but you're only returning the user id and the process's result. The rest of my questions and corrections will go in the reviews.
As a final note, I see you fixed a slight issue with the Playlist class in this PR. Try to keep these unrelated changes separated.

**Comment by MMDPROJECT** [comment]
Alright thanks for reading PR and it's documentation in the codes. well I agree with you we can change the `jsonBody` to `requestBody` for clarification. 

Actually I have thought about it a little bit but I couldn't convince ma self to also put other information about the `user` in that `jsonBody` because most of our requests doesn't need anything more than just a `userId` from that `user`.  but now when I look at the code I realize that we need everything for that `editPersonalInfoRequest`. Thanks for your comprehensive review, we will fix that in a moment.
 
 Sorry but I can't see anything in the PR more that these comments, can you direct me to those?
 
 And about your final note I apologies for being unexperienced and done such a thing, I try to prevent that next time and thanks for noticing me.  
 
 I will complete changes by tonight.

**Comment by MMDPROJECT** [comment]
I have made the changes you wanted. @Retriever5500

**Comment by Retriever5500** [comment]
LGTM

**Pull request merged**
